name: Run Grants UI Docker

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Checkout Grants UI Repository
        uses: actions/checkout@v4
        with:
          repository: DEFRA/grants-ui
          path: grants-ui # Checks out the repo into a sub-folder named 'grants-ui'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'


      - name: Install dependencies (Current Repo)
        run: npm install

      - name: Run Grants UI (Land Grants) Docker
        working-directory: ./grants-ui
        run: npm run docker:landgrants:up

      - name: Run Local Tests
        run: npm run test:local
        env:
          # Ensure this secret is set in your GitHub Repository Secrets
          DEFRA_ID_USER_PASSWORD: ${{ secrets.DEFRA_ID_USER_PASSWORD }}
          # You may also need to set the baseUrl if the docker container
          # is mapped to a specific port on localhost
          # NODE_TLS_REJECT_UNAUTHORIZED: 0
