name: Integrated Journey Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  journey-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Journey Tests (Current Repo)
        uses: actions/checkout@v4

      - name: Checkout Grants UI
        uses: actions/checkout@v4
        with:
          repository: DEFRA/grants-ui
          path: grants-ui

      - name: Checkout Land Grants API
        uses: actions/checkout@v4
        with:
          repository: DEFRA/land-grants-api
          path: land-grants-api

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Journey Test Dependencies
        run: npm install

      - name: Start Grants UI Services
        working-directory: ./grants-ui
        run: npm run docker:landgrants:up

      - name: Run API Migrations
        working-directory: ./land-grants-api
        run: npm run docker:migrate:ext:up

      - name: Wait for Services
        # Giving Docker containers a moment to fully initialize
        run: sleep 15

      - name: Run Journey Tests
        run: npm run test:local
        env:
          DEFRA_ID_USER_PASSWORD: ${{ secrets.DEFRA_ID_USER_PASSWORD }}
