name: Run Journey Tests E2E against Grants UI and Land Grants API

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-ui:
    name: Pull Grants UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Grants UI
        uses: actions/checkout@v4
        with:
          repository: DEFRA/grants-ui
          path: grants-ui
      - name: Upload Grants UI Workspace
        uses: actions/upload-artifact@v4
        with:
          name: grants-ui-repo
          path: grants-ui/

  # Job 2: Pull Land Grants API in parallel
  setup-api:
    name: Pull Land Grants API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Land Grants API
        uses: actions/checkout@v4
        with:
          repository: DEFRA/land-grants-api
          path: land-grants-api
      - name: Upload API Workspace
        uses: actions/upload-artifact@v4
        with:
          name: land-grants-api-repo
          path: land-grants-api/

  api-migrations:
    name: Run Land Grants API Migrations
    runs-on: ubuntu-latest
    needs: [setup-ui, setup-api]
    steps:
      - name: Download Grants UI
        uses: actions/download-artifact@v4
        with:
          name: grants-ui-repo
          path: grants-ui

      - name: Download Land Grants API
        uses: actions/download-artifact@v4
        with:
          name: land-grants-api-repo
          path: land-grants-api

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Journey Test Dependencies
        working-directory: ./land-grants-api
        run: npm ci

      - name: Start Grants UI Services
        working-directory: ./grants-ui
        run: npm run docker:landgrants:up


  # Job 4: Run services and tests once Job 1 and 2 are done
  run-tests:
    name: Run Journey Tests for a single application
    runs-on: ubuntu-latest
    needs: [api-migrations]
    steps:
      - name: Checkout Journey Tests (Current Repo)
        uses: actions/checkout@v4

      - name: Download Grants UI
        uses: actions/download-artifact@v4
        with:
          name: grants-ui-repo
          path: grants-ui

      - name: Download Land Grants API
        uses: actions/download-artifact@v4
        with:
          name: land-grants-api-repo
          path: land-grants-api

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Journey Test Dependencies
        run: npm install

      - name: Run Local Journey Tests
        run: npm run test:local
        env:
          DEFRA_ID_USER_PASSWORD: ${{ secrets.DEFRA_ID_USER_PASSWORD }}
